baseurl = "/"
title = "NullSpectra"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "NullSpectra"
    description = "This is my blog about technology."
    opengraph = true
    shareTwitter = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
